esphome:
  name: generic-st7701s-display
  friendly_name: Generic ST7701S Display
  
  # CRITICAL: Delay Wi-Fi startup to allow VCOM charge pump to stabilize
  on_boot:
    - then: 
        - logger.log: "Waiting 10s for Display VCOM to fully stabilize before Wi-Fi..."
        - delay: 10s 
        - logger.log: "Display stabilized. Starting Wi-Fi..."
        - wifi.enable: 
        - delay: 1s

esp32:
  board: esp32-s3-devkitc-1 # Adjust board if necessary
  flash_size: 16MB
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      # --- Critical PSRAM settings for stability ---
      CONFIG_SPIRAM: y
      CONFIG_SPIRAM_MODE_OCT: y
      CONFIG_SPIRAM_SPEED_80M: y
      CONFIG_SPIRAM_BOOT_INIT: y
      CONFIG_SPIRAM_USE_CAPS_ALLOC: y
      CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL: "8192"
      CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL: "65536"
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: y
      CONFIG_SPIRAM_USE_MALLOC: y
      
# ... (API, OTA, Logger, etc. sections omitted for brevity)

i2c:
  - id: i2c_bus
    sda: GPIO15
    scl: GPIO07
    scan: true

spi:
  - id: spi_lcd
    clk_pin: GPIO02
    mosi_pin: GPIO01
    interface: spi3

# Ensure your IO Expander (e.g., PCA9554) matches this address and pins
pca9554:
  - id: p_c_a
    address: 0x20
    i2c_id: i2c_bus

# ... (Light/Backlight PWM config omitted for brevity)

display:
  - platform: st7701s
    id: my_display
    spi_id: spi_lcd
    spi_mode: MODE1
    color_order: bgr 
    update_interval: 1s # Use 'never' for LVGL/fast updates
    dimensions:
      width: 480
      height: 640
    rotation: 90
    cs_pin:
      pca9554: p_c_a
      number: 2
    reset_pin:
      pca9554: p_c_a
      number: 0
    de_pin: GPIO40
    hsync_pin: GPIO38
    vsync_pin: GPIO39
    pclk_pin: GPIO41
    data_rate: 8MHz 
    
    # CRITICAL: DEFINITIVE 2.8-INCH ST7701S INITIALIZATION SEQUENCE
    init_sequence:
      # --- Page 1 (0x13) Commands ---
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x13 ]
      - [ 0xEF, 0x08 ]
      # --- Page 0 (0x10) Commands ---
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x10 ]
      - [ 0xC0, 0x4F, 0x00 ]
      - [ 0xC1, 0x10, 0x02 ]
      - [ 0xC2, 0x07, 0x02 ]
      - [ 0xCC, 0x10 ]
      - [ 0xB0, 0x00, 0x10, 0x17, 0x0D, 0x11, 0x06, 0x05, 0x08, 0x07, 0x1F, 0x04, 0x11, 0x0E, 0x29, 0x30, 0x1F ] # Positive Gamma
      - [ 0xB1, 0x00, 0x0D, 0x14, 0x0E, 0x11, 0x06, 0x04, 0x08, 0x08, 0x20, 0x05, 0x13, 0x13, 0x26, 0x30, 0x1F ] # Negative Gamma
      # --- Page 2 (0x11) Commands ---
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x11 ]
      - [ 0xB0, 0x65 ]
      - [ 0xB1, 0x71 ]
      - [ 0xB2, 0x82 ]
      - [ 0xB3, 0x80 ]
      - [ 0xB5, 0x42 ]
      - [ 0xB7, 0x85 ]
      - [ 0xB8, 0x20 ]
      - [ 0xC0, 0x09 ]
      - [ 0xC1, 0x78 ]
      - [ 0xC2, 0x78 ]
      - [ 0xD0, 0x88 ]
      - [ 0xEE, 0x42 ]
      - [ 0xE0, 0x00, 0x00, 0x02 ]
      - [ 0xE1, 0x04, 0xA0, 0x06, 0xA0, 0x05, 0xA0, 0x07, 0xA0, 0x00, 0x44, 0x44 ]
      - [ 0xE2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 ]
      - [ 0xE3, 0x00, 0x00, 0x22, 0x22 ]
      - [ 0xE4, 0x44, 0x44 ]
      - [ 0xE5, 0x0C, 0x90, 0xA0, 0xA0, 0x0E, 0x92, 0xA0, 0xA0, 0x08, 0x8C, 0xA0, 0xA0, 0x0A, 0x8E, 0xA0, 0xA0 ]
      - [ 0xE6, 0x00, 0x00, 0x22, 0x22 ]
      - [ 0xE7, 0x44, 0x44 ]
      - [ 0xE8, 0x0D, 0x91, 0xA0, 0xA0, 0x0F, 0x93, 0xA0, 0xA0, 0x09, 0x8D, 0xA0, 0xA0, 0x0B, 0x8F, 0xA0, 0xA0 ]
      - [ 0xEB, 0x00, 0x00, 0xE4, 0xE4, 0x44, 0x00, 0x40 ]
      - [ 0xED, 0xFF, 0xF5, 0x47, 0x6F, 0x0B, 0xA1, 0xAB, 0xFF, 0xFF, 0xBA, 0x1A, 0xB0, 0xF6, 0x74, 0x5F, 0xFF ]
      - [ 0xEF, 0x08, 0x08, 0x08, 0x40, 0x3F, 0x64 ]
      
      # --- Final Operational Sequence (Crucial for Power On) ---
      # Revert to Command Page 0 (0x00)
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x00 ]
      # E6/E8 commands again
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x13 ]
      - [ 0xE6, 0x16, 0x7C ]
      - [ 0xE8, 0x00, 0x0E ]
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x00 ]
      # Sleep Out + required delay
      - [ 0x11 ]
      - delay 200ms
      # E8 command with 150ms delay
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x13 ]
      - [ 0xE8, 0x00, 0x0C ]
      - delay 150ms
      - [ 0xE8, 0x00, 0x00 ]
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x00 ]
      # Tearing Effect Line OFF
      - [ 0x35, 0x00 ] 
      # Display ON + required final delay
      - [ 0x29 ]
      - delay 100ms
      # --- LVGL/ESPHome-Specific Commands ---
      # Set Pixel Format to 16-bit RGB (0x55) - Mandatory for correct LVGL colors
      - [ 0x3A, 0x55 ]
      # Set Memory Access Control (MADCTL) for 90-degree rotation (MV=1, MY=1, BGR=1)
      - [ 0x36, 0xA0 ]
      
    data_pins:
      red:
        - 46
        - 3
        - 8
        - 18
        - 17
      green:
        - 14
        - 13
        - 12
        - 11
        - 10
        - 9
      blue:
        - 5
        - 45
        - 48
        - 47
        - 21

touchscreen:
  - platform: gt911
    id: my_touchscreen
    i2c_id: i2c_bus
    interrupt_pin: GPIO16
    reset_pin:
      pca9554: p_c_a
      number: 1
# ... (LVGL Configuration, Sensors, Time, etc. sections omitted for brevity)
