# ══════════════════════════════════════════════════════════════════════════════
# ESPHome Configuration for Waveshare ESP32-S3 2.8" Touch LCD (ST7701S)
# ══════════════════════════════════════════════════════════════════════════════
# Hardware: Waveshare ESP32-S3 Touch LCD 2.8B (480x640 ST7701S + GT911 Touch)
# Board: ESP32-S3-DevKitC-1 with 16MB Flash, 8MB PSRAM
# Display: ST7701S RGB interface with 16-bit parallel data
# Touch: GT911 capacitive touch controller via I2C
# 
substitutions:
  name: tommy-kincony-display
  friendly_name: "Tommy Kincony Display"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: backlight
          brightness: 100%
      - lvgl.page.show: main_page
      - script.execute: user_activity

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: eir92262635
  password: DKKUGnvVpn
  power_save_mode: none

i2c:
  id: i2c_bus
  sda: GPIO15
  scl: GPIO7
  frequency: 800kHz
  scan: true

pca9554:
  - id: exio
    i2c_id: i2c_bus
    address: 0x20
    pin_count: 8

spi:
  id: lcd_spi
  clk_pin: GPIO2
  mosi_pin: GPIO1

output:
  - platform: ledc
    id: backlight_pwm
    pin: GPIO6
    frequency: 20000 Hz

light:
  - platform: monochromatic
    id: backlight
    name: "LCD Backlight"
    output: backlight_pwm
    restore_mode: ALWAYS_ON
    default_transition_length: 0ms
    gamma_correct: 1.0

# =========================
# Touch (GT911) + wake
# =========================
touchscreen:
  - platform: gt911
    id: touch
    i2c_id: i2c_bus
    address: 0x5D
    interrupt_pin: GPIO16
    reset_pin:
      pca9554: exio
      number: 1
    on_touch:
      then:
        - script.execute: user_activity

display:
  - platform: mipi_rgb
    id: lcd
    model: CUSTOM
    spi_id: lcd_spi

    cs_pin:
      pca9554: exio
      number: 2
    reset_pin:
      pca9554: exio
      number: 0

    data_rate: 80MHz
    spi_mode: MODE0
    color_order: RGB
    invert_colors: false

    dimensions:
      width: 480
      height: 640

    # ROCK STEADY SETTINGS
    pclk_frequency: 16MHz
    pclk_inverted: false

    hsync_pulse_width: 10
    hsync_back_porch: 70
    hsync_front_porch: 60
    vsync_pulse_width: 10
    vsync_back_porch: 20
    vsync_front_porch: 20

    de_pin: GPIO40
    hsync_pin: GPIO38
    vsync_pin: GPIO39
    pclk_pin: GPIO41

    data_pins:
      red:   [GPIO46, GPIO3, GPIO8, GPIO18, GPIO17]
      green: [GPIO14, GPIO13, GPIO12, GPIO11, GPIO10, GPIO9]
      blue:  [GPIO5, GPIO45, GPIO48, GPIO47, GPIO21]

    init_sequence:
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x13]
      - [0xEF, 0x08]
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x10]
      - [0xC0, 0x4F, 0x00]
      - [0xC1, 0x10, 0x02]
      - [0xC2, 0x07, 0x02]
      - [0xCC, 0x10]
      - [0xB0, 0x00, 0x10, 0x17, 0x0D, 0x11, 0x06, 0x05, 0x08, 0x07, 0x1F, 0x04, 0x11, 0x0E, 0x29, 0x30, 0x1F]
      - [0xB1, 0x00, 0x0D, 0x14, 0x0E, 0x11, 0x06, 0x04, 0x08, 0x08, 0x20, 0x05, 0x13, 0x13, 0x26, 0x30, 0x1F]
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x11]
      - [0xB0, 0x65]
      - [0xB1, 0x71]
      - [0xB2, 0x82]
      - [0xB3, 0x80]
      - [0xB5, 0x42]
      - [0xB7, 0x85]
      - [0xB8, 0x20]
      - [0xC0, 0x09]
      - [0xC1, 0x78]
      - [0xC2, 0x78]
      - [0xD0, 0x88]
      - [0xEE, 0x42]
      - [0xE0, 0x00, 0x00, 0x02]
      - [0xE1, 0x04, 0xA0, 0x06, 0xA0, 0x05, 0xA0, 0x07, 0xA0, 0x00, 0x44, 0x44]
      - [0xE2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      - [0xE3, 0x00, 0x00, 0x22, 0x22]
      - [0xE4, 0x44, 0x44]
      - [0xE5, 0x0C, 0x90, 0xA0, 0xA0, 0x0E, 0x92, 0xA0, 0xA0, 0x08, 0x8C, 0xA0, 0xA0, 0x0A, 0x8E, 0xA0, 0xA0]
      - [0xE6, 0x00, 0x00, 0x22, 0x22]
      - [0xE7, 0x44, 0x44]
      - [0xE8, 0x0D, 0x91, 0xA0, 0xA0, 0x0F, 0x93, 0xA0, 0xA0, 0x09, 0x8D, 0xA0, 0xA0, 0x0B, 0x8F, 0xA0, 0xA0]
      - [0xEB, 0x00, 0x00, 0xE4, 0xE4, 0x44, 0x00, 0x40]
      - [0xED, 0xFF, 0xF5, 0x47, 0x6F, 0x0B, 0xA1, 0xAB, 0xFF, 0xFF, 0xBA, 0x1A, 0xB0, 0xF6, 0x74, 0x5F, 0xFF]
      - [0xEF, 0x08, 0x08, 0x08, 0x40, 0x3F, 0x64]
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x00]
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x13]
      - [0xE6, 0x16, 0x7C]
      - [0xE8, 0x00, 0x0E]
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x00]
      - [0x11]
      - delay 200ms
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x13]
      - [0xE8, 0x00, 0x0C]
      - delay 150ms
      - [0xE8, 0x00, 0x00]
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x00]
      - [0x35, 0x00]

font:
  - file: "gfonts://Inter"
    id: font_small
    size: 18
    bpp: 2
  - file: "gfonts://Inter"
    id: font_medium
    size: 24
    bpp: 2
  - file: "gfonts://Inter"
    id: font_large
    size: 36
    bpp: 2
  - file: "gfonts://Inter"
    id: font_sleep
    size: 66
    bpp: 2

time:
  - platform: homeassistant
    id: ha_time

sensor:
  - platform: homeassistant
    id: immersion_watts
    entity_id: sensor.0xa4c13874272b4470_power_b
    on_value:
      then:
        - lvgl.label.update:
            id: lbl_watts
            text: !lambda |-
              char buf[16];
              snprintf(buf, sizeof(buf), "%.0fW", x);
              return std::string(buf);

  - platform: homeassistant
    id: immersion_amps
    entity_id: sensor.0xa4c13874272b4470_current_b
    on_value:
      then:
        - lvgl.label.update:
            id: lbl_amps
            text: !lambda |-
              char buf[16];
              snprintf(buf, sizeof(buf), "%.2fA", x);
              return std::string(buf);

# =========================
# Idle / Sleep logic
# =========================
globals:
  - id: last_touch_ms
    type: uint32_t
    restore_value: no
    initial_value: "0"
  - id: is_sleeping
    type: bool
    restore_value: no
    initial_value: "false"

script:
  - id: user_activity
    mode: restart
    then:
      - lambda: |-
          id(last_touch_ms) = millis();
          if (id(is_sleeping)) {
            id(is_sleeping) = false;
          }
      - lvgl.page.show: main_page
      - light.turn_on:
          id: backlight
          brightness: 100%

  - id: go_to_sleep
    mode: restart
    then:
      - lambda: |-
          id(is_sleeping) = true;
      - lvgl.page.show: sleep_page
      # dim to a visible-but-not-blinding level
      - light.turn_on:
          id: backlight
          brightness: 8%

interval:
  # update the time while awake
  - interval: 10s
    then:
      - if:
          condition:
            lambda: 'return !id(is_sleeping);'
          then:
            - lvgl.label.update:
                id: lbl_time
                text: !lambda |-
                  auto t = id(ha_time).now();
                  if (!t.is_valid()) return std::string("--:--");
                  char buf[8];
                  snprintf(buf, sizeof(buf), "%02d:%02d", t.hour, t.minute);
                  return std::string(buf);

  # sleep timer check (30s)
  - interval: 500ms
    then:
      - if:
          condition:
            lambda: |-
              if (id(is_sleeping)) return false;
              uint32_t elapsed = millis() - id(last_touch_ms);
              return elapsed > 30000;
          then:
            - script.execute: go_to_sleep

lvgl:
  log_level: WARN
  buffer_size: 35%
  displays:
    - lcd

  pages:
    - id: main_page
      bg_color: 0x000000
      widgets:
        - obj:
            width: 100%
            height: 100%
            bg_color: 0x000000
            border_width: 0
            pad_all: 0
            widgets:

              - obj:
                  width: 100%
                  height: 80
                  align: TOP_MID
                  bg_color: 0x2F2FD3
                  pad_all: 15
                  widgets:
                    - label:
                        text: "Hot Water"
                        text_font: font_medium
                        text_color: 0xFFFFFF
                        align: CENTER

              - obj:
                  width: 92%
                  height: 160
                  align: TOP_MID
                  y: 110
                  bg_color: 0x1E1E1E
                  radius: 18
                  pad_all: 20
                  widgets:
                    - label:
                        id: lbl_time
                        text: "--:--"
                        text_font: font_large
                        text_color: 0xFFFFFF
                        align: CENTER

              - obj:
                  width: 92%
                  height: 160
                  align: TOP_MID
                  y: 290
                  bg_color: 0x2C2C2C
                  radius: 18
                  pad_all: 20
                  widgets:
                    - label:
                        text: "Immersion Watts"
                        text_font: font_small
                        text_color: 0xBBBBBB
                        align: TOP_MID
                    - label:
                        id: lbl_watts
                        text: "--W"
                        text_font: font_large
                        text_color: 0xFFFFFF
                        align: CENTER
                        y: 30

              - obj:
                  width: 92%
                  height: 160
                  align: TOP_MID
                  y: 470
                  bg_color: 0x242424
                  radius: 18
                  pad_all: 20
                  widgets:
                    - label:
                        text: "Immersion Amps"
                        text_font: font_small
                        text_color: 0xBBBBBB
                        align: TOP_MID
                    - label:
                        id: lbl_amps
                        text: "0.00A"
                        text_font: font_large
                        text_color: 0xFFFFFF
                        align: CENTER
                        y: 30

    - id: sleep_page
      bg_color: 0x000000
      widgets:
        - label:
            text: "Tap to wake"
            text_font: font_sleep
            text_color: 0x7A7A7A
            align: CENTER

